/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      fontFamily: {
        display: ['"Space Grotesk"', '"Plus Jakarta Sans"', "sans-serif"],
        headline: ['"Space Grotesk"', '"Plus Jakarta Sans"', "sans-serif"],
        body: ['"Plus Jakarta Sans"', "Inter", "sans-serif"],
        "label-caps": ['"Plus Jakarta Sans"', "Inter", "sans-serif"],
        "data-tabular": ['"JetBrains Mono"', "monospace"],
      },
      fontSize: {
        "display-xl": ["4.5rem", { lineHeight: "0.98", letterSpacing: "-0.03em" }],
        "display-lg": ["3.25rem", { lineHeight: "1.02", letterSpacing: "-0.03em" }],
        "headline-lg": ["2.25rem", { lineHeight: "1.08", letterSpacing: "-0.02em" }],
        "headline-md": ["1.625rem", { lineHeight: "1.15", letterSpacing: "-0.01em" }],
        "body-lg": ["1rem", { lineHeight: "1.5" }],
        "body-md": ["0.875rem", { lineHeight: "1.5" }],
        "label-caps": ["0.6875rem", { lineHeight: "1.2", letterSpacing: "0.08em" }],
        "data-tabular": ["0.8125rem", { lineHeight: "1.4" }],
      },
      spacing: {
        xs: "0.25rem",
        sm: "0.5rem",
        md: "1rem",
        lg: "1.5rem",
        xl: "2.5rem",
        gutter: "1.25rem",
      },
      maxWidth: { "container-max": "1600px" },
      borderRadius: { DEFAULT: "1rem", xl2: "1.5rem" },
      borderWidth: { 3: "3px" },
      boxShadow: {
        pop: "4px 4px 0 0 rgba(43,43,47,1)",
        "pop-sm": "3px 3px 0 0 rgba(43,43,47,1)",
        "pop-lg": "6px 6px 0 0 rgba(43,43,47,1)",
        "pop-primary": "4px 4px 0 0 rgba(181,18,27,1)",
        "pop-hover": "6px 6px 0 0 rgba(43,43,47,1)",
        soft: "0 12px 32px rgba(43,43,47,0.08)",
        "soft-lg": "0 24px 60px rgba(43,43,47,0.12)",
      },
      colors: {
        background: "#F8F8F8",
        surface: "#FFFFFF",
        "surface-dim": "#F0F0F0",
        "surface-bright": "#FFFFFF",
        "surface-container-lowest": "#FFFFFF",
        "surface-container-low": "#FCFCFC",
        "surface-container": "#F3F3F3",
        "surface-container-high": "#EBEBEB",
        "surface-container-highest": "#E2E2E2",
        "surface-variant": "#EDEDED",
        "on-surface": "#2B2B2F",
        "on-surface-variant": "#63636A",
        outline: "#2B2B2F",
        "outline-variant": "#D8D8D8",
        primary: "#B5121B",
        "primary-container": "#B5121B",
        "on-primary": "#FFFFFF",
        "on-primary-container": "#FFFFFF",
        "primary-fixed": "#F3D3D5",
        "on-primary-fixed": "#3A0A0E",
        "on-primary-fixed-variant": "#7A0D15",
        secondary: "#2B2B2F",
        "secondary-container": "#2B2B2F",
        "on-secondary-container": "#FFFFFF",
        "secondary-fixed": "#D4D4D6",
        tertiary: "#7B61FF",
        "tertiary-container": "#7B61FF",
        error: "#B5121B",
        "error-container": "#B5121B",
        "on-error": "#FFFFFF",
        success: "#0F9D6E",
        "success-container": "#38D9A9",
        "on-success": "#FFFFFF",
        warning: "#B8860B",
        "warning-container": "#FFD84D",
        "on-warning": "#2B2B2F",
        /* Memphis accent palette */
        sunshine: "#FFD84D",
        violet: "#7B61FF",
        mint: "#38D9A9",
        tangerine: "#FFB347",
        sky: "#4D96FF",
      },
      keyframes: {
        "fade-in-up": {
          "0%": { opacity: "0", transform: "translate3d(0,16px,0) scale(0.98)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "fade-in": {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        "slide-in-left": {
          "0%": { opacity: "0", transform: "translate3d(-24px,0,0)" },
          "100%": { opacity: "1", transform: "translate3d(0,0,0)" },
        },
        "slide-in-right": {
          "0%": { opacity: "0", transform: "translate3d(24px,0,0)" },
          "100%": { opacity: "1", transform: "translate3d(0,0,0)" },
        },
        "rise-in": {
          "0%": { opacity: "0", transform: "translate3d(0,18px,0) scale(0.95)" },
          "100%": { opacity: "1", transform: "translate3d(0,0,0) scale(1)" },
        },
        "pulse-ring": {
          "0%, 100%": { opacity: "0.25", transform: "scale(0.95)" },
          "50%": { opacity: "1", transform: "scale(1.08)" },
        },
        "shimmer-x": {
          "0%": { transform: "translate3d(-100%,0,0)" },
          "100%": { transform: "translate3d(100%,0,0)" },
        },
        "float-gentle": {
          "0%, 100%": { transform: "translate3d(0,0,0)" },
          "50%": { transform: "translate3d(0,-6px,0)" },
        },
        "scan-line": {
          "0%": { transform: "translate3d(-120%,0,0)" },
          "100%": { transform: "translate3d(120%,0,0)" },
        },
        shimmer: {
          "100%": { transform: "translateX(100%)" },
        },
        "truck-enter": {
          "0%": { transform: "translateX(-110%)" },
          "100%": { transform: "translateX(0%)" },
        },
        "truck-exit": {
          "0%": { transform: "translateX(0%)", opacity: "1" },
          "100%": { transform: "translateX(110%)", opacity: "0" },
        },
        "wheel-spin": {
          to: { transform: "rotate(360deg)" },
        },
        "suspension-bob": {
          "0%, 100%": { transform: "translateY(0px)" },
          "50%": { transform: "translateY(-2px)" },
        },
        "dust-puff": {
          "0%": { transform: "translate(0,0) scale(0)", opacity: "0.7" },
          "50%": { opacity: "0.4" },
          "100%": { transform: "translate(-24px,-10px) scale(2.5)", opacity: "0" },
        },
        "headlight-flicker": {
          "0%, 100%": { opacity: "0.7" },
          "50%": { opacity: "1" },
        },
        "loader-fade-in": {
          from: { opacity: "0", transform: "scale(0.97)" },
          to: { opacity: "1", transform: "scale(1)" },
        },
        "loader-fade-out": {
          from: { opacity: "1", transform: "scale(1)" },
          to: { opacity: "0", transform: "scale(1.02)" },
        },
        "text-rise": {
          from: { opacity: "0", transform: "translateY(14px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        "logo-pop": {
          "0%": { opacity: "0", transform: "scale(0.7) rotate(-6deg)" },
          "70%": { transform: "scale(1.08) rotate(1deg)" },
          "100%": { opacity: "1", transform: "scale(1) rotate(0deg)" },
        },
        "marker-pop": {
          "0%": { opacity: "0", transform: "translate(-50%,-100%) scale(0.3)" },
          "70%": { transform: "translate(-50%,-100%) scale(1.15)" },
          "100%": { opacity: "1", transform: "translate(-50%,-100%) scale(1)" },
        },
        "marker-pulse": {
          "0%, 100%": { transform: "scale(0.8)", opacity: "0" },
          "40%": { transform: "scale(1.6)", opacity: "0.5" },
          "80%": { transform: "scale(2.2)", opacity: "0" },
        },
        "count-up": {
          from: { opacity: "0", transform: "translateY(8px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        "bar-grow": {
          from: { transform: "scaleY(0)" },
          to: { transform: "scaleY(1)" },
        },
        "road-dash": {
          to: { strokeDashoffset: "-40" },
        },
        wiggle: {
          "0%, 100%": { transform: "rotate(-3deg)" },
          "50%": { transform: "rotate(3deg)" },
        },
        "float-slow": {
          "0%, 100%": { transform: "translate3d(0,0,0) rotate(-2deg)" },
          "50%": { transform: "translate3d(0,-10px,0) rotate(2deg)" },
        },
        "pop-in": {
          "0%": { opacity: "0", transform: "scale(0.85) rotate(-4deg)" },
          "100%": { opacity: "1", transform: "scale(1) rotate(0deg)" },
        },
        "spin-slow": {
          to: { transform: "rotate(360deg)" },
        },
      },
      animation: {
        "fade-in-up": "fade-in-up 0.55s cubic-bezier(0.22,1,0.36,1) forwards",
        "fade-in": "fade-in 0.35s cubic-bezier(0.22,1,0.36,1) forwards",
        "slide-in-left": "slide-in-left 0.55s cubic-bezier(0.22,1,0.36,1) forwards",
        "slide-in-right": "slide-in-right 0.55s cubic-bezier(0.22,1,0.36,1) forwards",
        "rise-in": "rise-in 0.55s cubic-bezier(0.22,1,0.36,1) forwards",
        "pulse-ring": "pulse-ring 2.4s ease-in-out infinite",
        "float-gentle": "float-gentle 5s ease-in-out infinite",
        "scan-line": "scan-line 1.8s ease-in-out infinite",
        shimmer: "shimmer 1.5s infinite",
        "truck-enter": "truck-enter 0.9s cubic-bezier(0.22,1,0.36,1) forwards",
        "truck-exit": "truck-exit 0.6s cubic-bezier(0.55,0,1,0.45) forwards",
        "wheel-spin": "wheel-spin 0.4s linear infinite",
        "suspension-bob": "suspension-bob 0.5s ease-in-out infinite",
        "dust-puff": "dust-puff 0.8s ease-out infinite",
        "dust-puff2": "dust-puff2 0.9s ease-out 0.2s infinite",
        "headlight-flicker": "headlight-flicker 1.5s ease-in-out infinite",
        "loader-fade-in": "loader-fade-in 0.5s cubic-bezier(0.22,1,0.36,1) forwards",
        "loader-fade-out": "loader-fade-out 0.45s cubic-bezier(0.55,0,1,0.45) forwards",
        "text-rise": "text-rise 0.7s cubic-bezier(0.22,1,0.36,1) forwards",
        "logo-pop": "logo-pop 0.6s cubic-bezier(0.22,1,0.36,1) forwards",
        "marker-pop": "marker-pop 0.5s cubic-bezier(0.22,1,0.36,1) forwards",
        "count-up": "count-up 0.5s cubic-bezier(0.22,1,0.36,1) forwards",
        "bar-grow": "bar-grow 0.8s cubic-bezier(0.22,1,0.36,1) forwards",
        "road-dash": "road-dash 0.4s linear infinite",
        "marker-pulse": "marker-pulse 2.4s ease-in-out infinite",
        wiggle: "wiggle 3.5s ease-in-out infinite",
        "float-slow": "float-slow 6s ease-in-out infinite",
        "pop-in": "pop-in 0.5s cubic-bezier(0.22,1,0.36,1) forwards",
        "spin-slow": "spin-slow 12s linear infinite",
      },
    },
  },
  plugins: [],
};