/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      fontFamily: {
        display: ['"Plus Jakarta Sans"', "sans-serif"],
        headline: ['"Plus Jakarta Sans"', "sans-serif"],
        body: ['Inter', "sans-serif"],
        "label-caps": ['Inter', "sans-serif"],
        "data-tabular": ['"JetBrains Mono"', "monospace"],
      },
      fontSize: {
        "display-lg": ["2.75rem", { lineHeight: "1.05", letterSpacing: "-0.02em" }],
        "headline-lg": ["2rem", { lineHeight: "1.1", letterSpacing: "-0.01em" }],
        "headline-md": ["1.5rem", { lineHeight: "1.2" }],
        "body-lg": ["1rem", { lineHeight: "1.5" }],
        "body-md": ["0.875rem", { lineHeight: "1.5" }],
        "label-caps": ["0.6875rem", { lineHeight: "1.2", letterSpacing: "0.08em" }],
        "data-tabular": ["0.8125rem", { lineHeight: "1.4" }],
      },
      spacing: {
        xs: "0.25rem",
        sm: "0.5rem",
        md: "1rem",
        lg: "1.5rem",
        xl: "2.5rem",
        gutter: "1.25rem",
      },
      maxWidth: { "container-max": "1600px" },
      borderRadius: { DEFAULT: "0.5rem" },
      colors: {
        background: "#F8F9FB",
        surface: "#FFFFFF",
        "surface-dim": "#EEF0F3",
        "surface-bright": "#FFFFFF",
        "surface-container-lowest": "#FFFFFF",
        "surface-container-low": "#FBFBFC",
        "surface-container": "#F1F2F5",
        "surface-container-high": "#E9EAED",
        "surface-container-highest": "#E1E3E7",
        "surface-variant": "#E4E6EA",
        "on-surface": "#1D1D1F",
        "on-surface-variant": "#5B5D63",
        outline: "#C7C9CE",
        "outline-variant": "#DEE0E3",
        primary: "#B5121B",
        "primary-container": "#B5121B",
        "on-primary": "#FFFFFF",
        "on-primary-container": "#FFFFFF",
        "primary-fixed": "#F3D3D5",
        "on-primary-fixed": "#3A0A0E",
        "on-primary-fixed-variant": "#7A0D15",
        secondary: "#2B2B2F",
        "secondary-container": "#2B2B2F",
        "on-secondary-container": "#FFFFFF",
        "secondary-fixed": "#D4D4D6",
        tertiary: "#6B6B70",
        "tertiary-container": "#6B6B70",
        error: "#D32F2F",
        "error-container": "#D32F2F",
        "on-error": "#FFFFFF",
        success: "#1E8E5A",
        "success-container": "#1E8E5A",
        "on-success": "#FFFFFF",
        warning: "#C77700",
        "warning-container": "#C77700",
        "on-warning": "#FFFFFF",
      },
      keyframes: {
        "fade-in-up": {
          "0%": { opacity: "0", transform: "translate3d(0,16px,0) scale(0.98)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "fade-in": {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        "slide-in-left": {
          "0%": { opacity: "0", transform: "translate3d(-24px,0,0)" },
          "100%": { opacity: "1", transform: "translate3d(0,0,0)" },
        },
        "slide-in-right": {
          "0%": { opacity: "0", transform: "translate3d(24px,0,0)" },
          "100%": { opacity: "1", transform: "translate3d(0,0,0)" },
        },
        "rise-in": {
          "0%": { opacity: "0", transform: "translate3d(0,18px,0) scale(0.95)" },
          "100%": { opacity: "1", transform: "translate3d(0,0,0) scale(1)" },
        },
        "pulse-ring": {
          "0%, 100%": { opacity: "0.25", transform: "scale(0.95)" },
          "50%": { opacity: "1", transform: "scale(1.08)" },
        },
        "shimmer-x": {
          "0%": { transform: "translate3d(-100%,0,0)" },
          "100%": { transform: "translate3d(100%,0,0)" },
        },
        "float-gentle": {
          "0%, 100%": { transform: "translate3d(0,0,0)" },
          "50%": { transform: "translate3d(0,-6px,0)" },
        },
        "scan-line": {
          "0%": { transform: "translate3d(-120%,0,0)" },
          "100%": { transform: "translate3d(120%,0,0)" },
        },
        shimmer: {
          "100%": { transform: "translateX(100%)" },
        },
      },
      animation: {
        "fade-in-up": "fade-in-up 0.55s cubic-bezier(0.22,1,0.36,1) forwards",
        "fade-in": "fade-in 0.35s cubic-bezier(0.22,1,0.36,1) forwards",
        "slide-in-left": "slide-in-left 0.55s cubic-bezier(0.22,1,0.36,1) forwards",
        "slide-in-right": "slide-in-right 0.55s cubic-bezier(0.22,1,0.36,1) forwards",
        "rise-in": "rise-in 0.55s cubic-bezier(0.22,1,0.36,1) forwards",
        "pulse-ring": "pulse-ring 2.4s ease-in-out infinite",
        "float-gentle": "float-gentle 5s ease-in-out infinite",
        "scan-line": "scan-line 1.8s ease-in-out infinite",
        shimmer: "shimmer 1.5s infinite",
      },
    },
  },
  plugins: [],
};